# Generated by Django 4.2.2 on 2024-09-05 17:07

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Награда за выполнение привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        verbose_name="Периодичность выполнения привычки в днях",
                    ),
                ),
                (
                    "action_duration",
                    models.CharField(
                        blank=True,
                        default=datetime.timedelta(seconds=120),
                        max_length=50,
                        verbose_name="Продолжительность выполнения действия",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "relation_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
