# Generated by Django 4.2.2 on 2024-09-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="first_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата первого выполнения"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="next_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата следующего выполнения"
            ),
        ),
    ]
